#pragma once

#include "BasePiece.h"

#include "WhiteWitch.h"
#include "King.h"
#include "WhiteKnight.h"
#include "WhiteAlchemist.h"
#include "WhiteArcher.h"
#include "WhiteBuilder.h"
#include "WhiteGrimReaper.h"
#include "WhitePlagueDoctor.h"
#include "WhiteRogue.h"
#include "WhiteTrebuchet.h"
#include "WhiteWarlord.h"
#include "WhiteSamurai.h"
#include "WhiteDragon.h"

#include "BlackWitch.h"
#include "BlackKnight.h"
#include "BlackAlchemist.h"
#include "BlackArcher.h"
#include "BlackBuilder.h"
#include "BlackGrimReaper.h"
#include "BlackPlagueDoctor.h"
#include "BlackRogue.h"
#include "BlackTrebuchet.h"
#include "BlackWarlord.h"
#include "BlackSamurai.h"
#include "BlackDragon.h"